name: Auto-label OS based on dropdown selection

on:
  issues:
    types:
      - opened

permissions:
  contents: read
  issues: write
jobs:
  label-os:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/bug-report.yaml

      - name: Set labels based on OS field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: os  # This matches the ID of the OS field in the issue form
          block-list: |
            None
            Other
          token: ${{ secrets.GITHUB_TOKEN }}
